### ISSUE TITLE
App crash (infinite loop) when adding station with "search stations"

### ISSUE THREAD

**Issue by fredsleeve** [Podcast-Republic/PRApp#446]
Hi,

I just encountered an infinite loop which causes the app to crash without an error message (app version: 24.6.24R).

Steps to reproduce:
1. Go to Radio stations
2. Click "+"
3. Search stations
4. Message dialogue "[null] is not found. Add this station by URL?" appears and re-appears until the whole app crashes, see screen recording: https://github.com/Podcast-Republic/PRApp/assets/67844445/2b03ab75-3485-4d9f-b3b1-70e3c9e64769

Please check if this is related to fix of issue #437.

**Comment by fredsleeve** [comment]
Update: Issue occurs also when searching for RSS feeds.

**Comment by gemiren** [comment]
Thanks for the bug report. This crash bug has been fixed in the latest beta version. Please join the beta program in the Play Store and then update to the latest beta version if you'd like to get the fix now.

**Comment by fredsleeve** [comment]
It's fixed with one the latest version, but the message "[null] is not found. Add this station by URL?" still occurs, before the screen jumps to the search tab.

**Comment by gemiren** [comment]
Will look into it and fix it asap. Thanks!

**Comment by fredsleeve** [comment]
The bug "[null] is not found" still exists. Any chance to get this fixed?

**Comment by gemiren** [comment]
> The bug "[null] is not found" still exists. Any chance to get this fixed?

I assume you mean the "[null]" in the message instead of the infinite looping and crashing, is that correct?

**Comment by fredsleeve** [comment]
Yes, I mean the [null] message, not the infinite loop (this is fixed).

[null] error occurs when you use the "+" search for radios, articles or RSS in your subscriptions. After this it also occurs in podcasts.

**Comment by gemiren** [comment]
Thanks very much for the clarification. It should be fixed now in today's beta update.

**Comment by fredsleeve** [comment]
Closing, fixed with 24.9.9b
