### ISSUE TITLE
Truncated text due to rounded corners

### ISSUE THREAD

**Issue by oldman63** [Podcast-Republic/PRApp#52]
Due to the "corners" of the rounded corners, the text at the bottom of the screen is truncated.

Tip: If the text appeared ABOVE the icons, apparent truncation could be avoided.

"Marked" red the rounded corners...

![Screenshot_20211110-074526_Podcast Republic-3](https://user-images.githubusercontent.com/3171626/141098522-6ec33551-1859-4a66-bceb-72150bd6cb1d.jpg)

**Comment by gemiren** [comment]
Text appears above does solve the problem but I haven't seen any app uses that yet. Also it's not recommended by Google Material design.

Starting with Android 12, Android does provide a new API to find if screen has round corners and apps can define a rounded corners to avoid cutout. That should fix this issue.

**Comment by oldman63** [comment]
I upgraded to Android 12 (Samsung SM-G975F, S10+), the problem persists even when all tabs are turned on.

The text on the two edge tabs appears truncated on the display due to the rounding of the display.
